/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almondessol;

import javax.swing.JOptionPane;

/**
 *
 * @author estevao
 */
public class TelaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaCadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnome = new javax.swing.JLabel();
        lcod = new javax.swing.JLabel();
        tnome = new javax.swing.JTextField();
        tcod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lmarca = new javax.swing.JLabel();
        tmarca = new javax.swing.JTextField();
        lmodelo = new javax.swing.JLabel();
        tmodelo = new javax.swing.JTextField();
        lpreco = new javax.swing.JLabel();
        tpreco = new javax.swing.JTextField();
        ltipo = new javax.swing.JLabel();
        ttipo = new javax.swing.JTextField();
        ldescricao = new javax.swing.JLabel();
        tdescricao = new javax.swing.JTextField();
        lquantidade = new javax.swing.JLabel();
        tquantidade = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lnome.setText("Nome");

        lcod.setText("Codigo");

        tnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("CADASTRAR INFORMAÇÕES");

        lmarca.setText("Marca");

        tmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmarcaActionPerformed(evt);
            }
        });

        lmodelo.setText("Modelo");

        tmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmodeloActionPerformed(evt);
            }
        });

        lpreco.setText("Preço");

        tpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprecoActionPerformed(evt);
            }
        });

        ltipo.setText("Tipo");

        ttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttipoActionPerformed(evt);
            }
        });

        ldescricao.setText("Descrição");

        tdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdescricaoActionPerformed(evt);
            }
        });

        lquantidade.setText("Quantidade");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lmodelo)
                        .addComponent(lmarca)
                        .addComponent(jLabel3)
                        .addComponent(lcod)
                        .addComponent(lnome)
                        .addComponent(tnome, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(tcod)
                        .addComponent(tmarca)
                        .addComponent(tmodelo))
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lpreco)
                        .addComponent(tpreco, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(ltipo)
                        .addComponent(ttipo)
                        .addComponent(ldescricao)
                        .addComponent(tdescricao)
                        .addComponent(lquantidade)
                        .addComponent(tquantidade))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnome)
                    .addComponent(lpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lmarca)
                    .addComponent(ldescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lmodelo)
                    .addComponent(lquantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmarcaActionPerformed

    private void tmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmodeloActionPerformed

    private void ttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttipoActionPerformed

    private void tdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdescricaoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        if(evt.getSource()==btnConfirmar){
            if(stringVazia(tnome.getText())==false || stringVazia(ttipo.getText())==false || stringVazia(tmarca.getText())==false || stringVazia(tpreco.getText())==false || stringVazia(tcod.getText())==false || stringVazia(tmodelo.getText())==false || stringVazia(tdescricao.getText())==false || stringVazia(tquantidade.getText())==false)
                JOptionPane.showMessageDialog(null, "Campo(s) vazio");
            if(precoNegativo(Integer.valueOf(tquantidade.getText())) == false)
                JOptionPane.showMessageDialog(null, "Quantidade menor que 0");
            if(quantNegativo(Integer.valueOf(tpreco.getText())) == false)
                JOptionPane.showMessageDialog(null, "Preço menor que 0");
            if(letrasEmCampoDeNumero(tquantidade.getText()) || letrasEmCampoDeNumero(tcod.getText()) || letrasEmCampoDeNumero(tpreco.getText()))
                JOptionPane.showMessageDialog(null, "Contém letras em campo(s) que deveria ter apenas número");
            if(numeroEmCampoDeLetras(tnome.getText())==false)
                JOptionPane.showMessageDialog(null, "Contém numerais no(s) campo(s) de nome ou instrumentos");
            else{
            
                ConexaoBanco banco = new ConexaoBanco();
                Instrumento instrumento = new Instrumento(
                        tnome.getText(),
                        tmarca.getText(),
                        tmodelo.getText(),
                        ttipo.getText(),
                        tdescricao.getText(),
                        Double.parseDouble(tpreco.getText()),
                        Integer.parseInt(tquantidade.getText()),
                        Integer.parseInt(tcod.getText())   
                );
                Object[] options = { "Sim", "Não" }; 

                int opcao = JOptionPane.showOptionDialog(null, "Deseja realmente Cadastrar?", "De novo?", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]); 

                if (opcao == 0){

                    banco.cadastrar(instrumento);
                    JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!!!");

                    // Limpa os campos após o cadastro
                    
                    tnome.setText("");
                    tmarca.setText("");
                    tmodelo.setText("");
                    ttipo.setText("");
                    tdescricao.setText("");
                    tpreco.setText("");
                    tquantidade.setText("");
                    tcod.setText("");
                    
                }              
            }            
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomeActionPerformed

    private void tprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprecoActionPerformed

    public boolean precoNegativo(int num){
        if(num<=0)
            return false;
        return true;
    }
    
    public boolean quantNegativo(int num){
        if(num<=0)
            return false;
        return true;
        
    }
    
    public boolean letrasEmCampoDeNumero(String num){
        if(num.matches("[0-9]+"))
            return false;
        return true;
    }
    
    public boolean numeroEmCampoDeLetras(String str){
        if(str.matches("(?:\\d+[a-z]|[a-z]+\\d)[a-z\\d]*"))
            return false;
        return true;
    }
    
    private boolean stringVazia(String nome){
        if(nome.isEmpty() || nome==null || nome.trim()=="")
            return false;
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lcod;
    private javax.swing.JLabel ldescricao;
    private javax.swing.JLabel lmarca;
    private javax.swing.JLabel lmodelo;
    private javax.swing.JLabel lnome;
    private javax.swing.JLabel lpreco;
    private javax.swing.JLabel lquantidade;
    private javax.swing.JLabel ltipo;
    private javax.swing.JTextField tcod;
    private javax.swing.JTextField tdescricao;
    private javax.swing.JTextField tmarca;
    private javax.swing.JTextField tmodelo;
    private javax.swing.JTextField tnome;
    private javax.swing.JTextField tpreco;
    private javax.swing.JTextField tquantidade;
    private javax.swing.JTextField ttipo;
    // End of variables declaration//GEN-END:variables
}
