/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAOProduto;
import Model.Produto;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author tomaz
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        setResizable(false);  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNoma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfqtd = new javax.swing.JTextField();
        tfpreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        btCad = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        verificaCode = new javax.swing.JLabel();
        l_verifica_cod = new javax.swing.JLabel();
        l_verifica_qtd = new javax.swing.JLabel();
        l_verifica_preco = new javax.swing.JLabel();

        setTitle("Cadastro de Produtos");

        jLabel1.setText("Código de Barras");

        tfCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodeActionPerformed(evt);
            }
        });
        tfCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodeKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome");

        tfNoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomaActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Quantidade");

        jLabel6.setText("Preço");

        tfqtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfqtdActionPerformed(evt);
            }
        });
        tfqtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfqtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfqtdKeyReleased(evt);
            }
        });

        tfpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprecoActionPerformed(evt);
            }
        });
        tfpreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfprecoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfprecoKeyReleased(evt);
            }
        });

        jLabel7.setText("Descrição");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        btCad.setText("Cadastrar");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNoma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(tfqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(99, 99, 99)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(tfpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(l_verifica_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(112, 112, 112)
                                            .addComponent(jLabel9))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(verificaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(l_verifica_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l_verifica_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificaCode))
                .addGap(3, 3, 3)
                .addComponent(l_verifica_cod)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_verifica_qtd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_verifica_preco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCad)
                    .addComponent(btCancelar))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        // TODO add your handling code here:
        try {
            if(verificarCampos()){
                DAOProduto operacaoDAO = new DAOProduto();
                Produto novoProduto = new Produto(
                        Integer.parseInt(tfCode.getText()),
                        Integer.parseInt(tfqtd.getText()),
                        tfNoma.getText(),
                        tfMarca.getText(),
                        tfModelo.getText(),
                        taDescricao.getText(),
                        Float.parseFloat(tfpreco.getText())
                );

                boolean verifica = operacaoDAO.save(novoProduto);
                limparCampos();

            }            
        } catch (Exception e) {
        }

               
    }//GEN-LAST:event_btCadActionPerformed

    private void tfCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfCodeActionPerformed

    private void tfNomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomaActionPerformed

    private void tfCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodeKeyPressed
        // TODO add your handling code here:
        try {
            int key = evt.getKeyCode();
            if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE) {        
                tfCode.setEditable(true);
                l_verifica_cod.setText("");
            }else{
                l_verifica_cod.setText("Digite somente números!!!");
                tfCode.setEditable(false);

            }            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tfCodeKeyPressed

    private void tfCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodeKeyReleased
        // TODO add your handling code here:
        try {
            DAOProduto operacaoDAO = new DAOProduto();
            boolean verifica = operacaoDAO.verificarCodBarras(tfCode.getText());
            if(verifica){
                l_verifica_cod.setText("Codigo de barras em usado");
                btCad.setEnabled(false);
            }else{
                btCad.setEnabled(true);
                l_verifica_cod.setText("");            
            }

        } catch (Exception e) {
        }
   
        
    }//GEN-LAST:event_tfCodeKeyReleased

    private void tfqtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfqtdKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE) {        
            tfqtd.setEditable(true);
            l_verifica_qtd.setText("");
            tfqtd.setBackground(Color.WHITE);
        }else{
            l_verifica_qtd.setText("Digite somente números!!!");
            tfqtd.setEditable(false);
            
        }
    }//GEN-LAST:event_tfqtdKeyPressed

    private void tfqtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfqtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfqtdActionPerformed

    private void tfprecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprecoKeyPressed
        // TODO add your handling code here:
        try {
            float key = evt.getKeyCode();
            if((key>=evt.VK_0 && key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE || key==KeyEvent.VK_PERIOD) {        
                tfpreco.setEditable(true);
                l_verifica_preco.setText("");
            }else{
                l_verifica_preco.setText("Caractere invalido");
                tfpreco.setEditable(false);

            }             
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tfprecoKeyPressed

    private void tfprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprecoActionPerformed

    private void tfqtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfqtdKeyReleased
        // TODO add your handling code here:
        try {
            if(Integer.parseInt(tfqtd.getText()) <= 0){
                l_verifica_qtd.setText("Valor invalido");
                btCad.setEnabled(false);
            }else{
                l_verifica_qtd.setText("");
                btCad.setEnabled(true);            
            }

        } catch (Exception ex) {
            
        }
        

    }//GEN-LAST:event_tfqtdKeyReleased

    private void tfprecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprecoKeyReleased
        // TODO add your handling code here:
        try {
            char letra = '.';
            char[] palavra = tfpreco.getText().toCharArray();
            int cont = 0;
            for (int i = 0; i < palavra.length; i++) {
                if (palavra[i] == letra) {
                    cont++;
                }
            }
            if (cont > 1){
                l_verifica_preco.setText("Invalido");
                btCad.setEnabled(false);
                               
            }else{
                btCad.setEnabled(true);
                l_verifica_preco.setText("");                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tfprecoKeyReleased

    private void limparCampos(){
        tfCode.setText("");
        tfqtd.setText("");
        tfNoma.setText("");
        tfMarca.setText("");
        tfModelo.setText("");
        taDescricao.setText("");
        tfpreco.setText("");        
    }
    
    private boolean verificarCampos(){
        if(CamposVazios()){
            return false;
        }
        return true;
    }
    
    
    private boolean CamposVazios(){
        if(tfCode.getText()==null || tfCode.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo codigo barras vazio!!!");
            return true;
        }
        if(tfNoma.getText()==null || tfNoma.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo nome vazio!!!");
             return true;
        }        
        if(tfMarca.getText()==null || tfMarca.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo marca vazio!!!");
            return true;
        }
        if(tfModelo.getText()==null || tfModelo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo modelo vazio!!!");
             return true;
        }

        if(tfpreco.getText()==null || tfpreco.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo preco vazio!!!");
             return true;
        }
        if(tfqtd.getText()==null || tfqtd.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo quantidade vazio!!!");
            return true;
        } 
        if(taDescricao.getText()==null || taDescricao.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo descricao vazio!!!");
             return true;
        }        
        return false;
    }      

      
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CadastroView().setVisible(true);
//            }
//        });
//    }s

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCad;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_verifica_cod;
    private javax.swing.JLabel l_verifica_preco;
    private javax.swing.JLabel l_verifica_qtd;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfCode;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNoma;
    private javax.swing.JTextField tfpreco;
    private javax.swing.JTextField tfqtd;
    private javax.swing.JLabel verificaCode;
    // End of variables declaration//GEN-END:variables
}
